// Generated by Tmds.DBus.Tool v0.92.0 with arguments: codegen --protocol-api /run/current-system/sw/share/dbus-1/interfaces/org.freedesktop.portal.Request.xml
// <auto-generated/>
#nullable enable
namespace request.DBus
{
    using System;
    using Tmds.DBus.Protocol;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    sealed partial class Request : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.portal.Request";
        public Request(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task CloseAsync()
        {
            return Connection.CallMethodAsync(CreateMessage());
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "Close");
                return writer.CreateMessage();
            }
        }
        public ValueTask<IDisposable> WatchResponseAsync(Action<Exception?, (uint Response, Dictionary<string, VariantValue> Results)> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
            => Connection.WatchSignalAsync(Destination, Path, DBusInterfaceName, "Response", (Message m, object? s) => MessageReader.Read_uaesv(m), handler, this, emitOnCapturedContext, flags);
    }
    static partial class ObjectFactory
    {
        public static Request CreateRequest(this DBusService service, ObjectPath path) => new Request(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static (uint, Dictionary<string, VariantValue>) Read_uaesv(Message message)
        {
            var reader = message.GetBodyReader();
            var arg0 = reader.ReadUInt32();
            var arg1 = reader.ReadDictionaryOfStringToVariantValue();
            return (arg0, arg1);
        }
    }
    file static class MessageWriterExtensions
    {
    }
}
