// Generated by Tmds.DBus.Tool v0.92.0 with arguments: codegen --protocol-api /run/current-system/sw/share/dbus-1/interfaces/org.freedesktop.portal.ScreenCast.xml
// <auto-generated/>
#nullable enable
namespace screencast.DBus
{
    using System;
    using Tmds.DBus.Protocol;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    interface IScreenCastProperties
    {
        uint? AvailableSourceTypes { get; }
        uint? AvailableCursorModes { get; }
        uint? Version { get; }
        bool HasAvailableSourceTypesChanged { get; }
        bool HasAvailableCursorModesChanged { get; }
        bool HasVersionChanged { get; }
        bool AreAllPropertiesSet();
        ScreenCastProperties EnsureAllPropertiesSet();
    }
    sealed class ScreenCastProperties : IScreenCastProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x7U; // 3 properties
        private static uint Flag(ScreenCastProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public ScreenCastProperties() { }
        #nullable disable
        [System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private ScreenCastProperties(bool _) { }
        #nullable enable
        private void EnsureSet(ScreenCastProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new InvalidOperationException("Property is not set.");
            }
        }
        private uint _availableSourceTypes = default!;
        public required uint AvailableSourceTypes
        {
            get { EnsureSet(ScreenCastProperty.AvailableSourceTypes); return _availableSourceTypes; }
            set { _availableSourceTypes = value; __set |= Flag(ScreenCastProperty.AvailableSourceTypes); }
        }
        private uint _availableCursorModes = default!;
        public required uint AvailableCursorModes
        {
            get { EnsureSet(ScreenCastProperty.AvailableCursorModes); return _availableCursorModes; }
            set { _availableCursorModes = value; __set |= Flag(ScreenCastProperty.AvailableCursorModes); }
        }
        private uint _version = default!;
        public required uint Version
        {
            get { EnsureSet(ScreenCastProperty.Version); return _version; }
            set { _version = value; __set |= Flag(ScreenCastProperty.Version); }
        }
        uint? IScreenCastProperties.AvailableSourceTypes
            => IsSet(ScreenCastProperty.AvailableSourceTypes) ? _availableSourceTypes : default(uint?);
        uint? IScreenCastProperties.AvailableCursorModes
            => IsSet(ScreenCastProperty.AvailableCursorModes) ? _availableCursorModes : default(uint?);
        uint? IScreenCastProperties.Version
            => IsSet(ScreenCastProperty.Version) ? _version : default(uint?);
        bool IScreenCastProperties.HasAvailableSourceTypesChanged
            => IsSet(ScreenCastProperty.AvailableSourceTypes) || IsInvalidated(ScreenCastProperty.AvailableSourceTypes);
        bool IScreenCastProperties.HasAvailableCursorModesChanged
            => IsSet(ScreenCastProperty.AvailableCursorModes) || IsInvalidated(ScreenCastProperty.AvailableCursorModes);
        bool IScreenCastProperties.HasVersionChanged
            => IsSet(ScreenCastProperty.Version) || IsInvalidated(ScreenCastProperty.Version);
        ScreenCastProperties IScreenCastProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static ScreenCastProperties CreateUninitialized() => new ScreenCastProperties(false);
        private bool HasFlag(uint flags, ScreenCastProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static ScreenCastProperty ParsePropertyName(string propertyName)
        {
            return propertyName switch
            {
                "AvailableSourceTypes" => ScreenCastProperty.AvailableSourceTypes,
                "AvailableCursorModes" => ScreenCastProperty.AvailableCursorModes,
                "version" => ScreenCastProperty.Version,
                _ => 0
            };
        }
        private bool IsSet(ScreenCastProperty property) => HasFlag(__set, property);
        private bool IsInvalidated(ScreenCastProperty property) => HasFlag(__invalidated, property);
        private void SetInvalidated(ScreenCastProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public void SetInvalidated(string propertyName) => SetInvalidated(ParsePropertyName(propertyName));
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static IScreenCastProperties ReadFrom(ref Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            ArrayEnd arrayEnd = reader.ReadArrayStart(DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "AvailableSourceTypes":
                        reader.ReadSignature("u"u8);
                        props.AvailableSourceTypes = reader.ReadUInt32();
                        break;
                    case "AvailableCursorModes":
                        reader.ReadSignature("u"u8);
                        props.AvailableCursorModes = reader.ReadUInt32();
                        break;
                    case "version":
                        reader.ReadSignature("u"u8);
                        props.Version = reader.ReadUInt32();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                ArrayEnd invalidatedEnd = reader.ReadArrayStart(DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "AvailableSourceTypes" => Flag(ScreenCastProperty.AvailableSourceTypes),
                        "AvailableCursorModes" => Flag(ScreenCastProperty.AvailableCursorModes),
                        "version" => Flag(ScreenCastProperty.Version),
                        _ => 0
                    };
                }
            }
            return props;
        }
        private enum ScreenCastProperty
        {
            UnknownProperty = 0,
            AvailableSourceTypes = 1,
            AvailableCursorModes = 2,
            Version = 3
        }
    }
    sealed partial class ScreenCast : Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.portal.ScreenCast";
        public ScreenCast(Tmds.DBus.Protocol.DBusConnection connection, string destination, ObjectPath path)
            : base(connection, destination, path)
        { }
        public Task<ObjectPath> CreateSessionAsync(Dictionary<string, VariantValue> options)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "a{sv}",
                    member: "CreateSession");
                writer.WriteDictionary(options);
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> SelectSourcesAsync(ObjectPath sessionHandle, Dictionary<string, VariantValue> options)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "oa{sv}",
                    member: "SelectSources");
                writer.WriteObjectPath(sessionHandle);
                writer.WriteDictionary(options);
                return writer.CreateMessage();
            }
        }
        public Task<ObjectPath> StartAsync(ObjectPath sessionHandle, string parentWindow, Dictionary<string, VariantValue> options)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_o(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "osa{sv}",
                    member: "Start");
                writer.WriteObjectPath(sessionHandle);
                writer.WriteString(parentWindow);
                writer.WriteDictionary(options);
                return writer.CreateMessage();
            }
        }
        public Task<System.Runtime.InteropServices.SafeHandle> OpenPipeWireRemoteAsync(ObjectPath sessionHandle, Dictionary<string, VariantValue> options)
        {
            return Connection.CallMethodAsync(CreateMessage(), (Message m, object? s) => MessageReader.Read_h(m), this);
            MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    signature: "oa{sv}",
                    member: "OpenPipeWireRemote");
                writer.WriteObjectPath(sessionHandle);
                writer.WriteDictionary(options);
                return writer.CreateMessage();
            }
        }
        public Task<uint> GetAvailableSourceTypesAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("AvailableSourceTypes"), (Message m, object? s) => MessageReader.Read_v_u(m), this);
        public Task<uint> GetAvailableCursorModesAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("AvailableCursorModes"), (Message m, object? s) => MessageReader.Read_v_u(m), this);
        public Task<uint> GetVersionAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("version"), (Message m, object? s) => MessageReader.Read_v_u(m), this);
        public async Task<IScreenCastProperties> GetPropertiesAsync()
        {
            var props = await Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (Message m, object? s) => ReadMessage(m), this).ConfigureAwait(false);
            props.EnsureAllPropertiesSet();
            return props;
            static IScreenCastProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                return ScreenCastProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public ValueTask<IDisposable> WatchPropertiesChangedAsync(Action<Exception?, IScreenCastProperties> handler, bool emitOnCapturedContext = true, ObserverFlags flags = ObserverFlags.None)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (Message m, object? s) => ReadMessage(m), handler, this, emitOnCapturedContext, flags);
            static IScreenCastProperties ReadMessage(Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return ScreenCastProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    static partial class ObjectFactory
    {
        public static ScreenCast CreateScreenCast(this DBusService service, ObjectPath path) => new ScreenCast(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static ObjectPath Read_o(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadObjectPath();
        }
        public static System.Runtime.InteropServices.SafeHandle Read_h(Message message)
        {
            var reader = message.GetBodyReader();
            return reader.ReadHandle<Microsoft.Win32.SafeHandles.SafeFileHandle>();
        }
        public static uint Read_v_u(Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("u"u8);
            return reader.ReadUInt32();
        }
    }
    file static class MessageWriterExtensions
    {
    }
}
